name: Continuous Integration for PR and code verification

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ] # optional, for main branch checks

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Security Scan
        run: npm audit --audit-level=high || true

      - name: Test
        run: npm test -- --ci --coverage
